### ISSUE TITLE
Regions with coasts not allowing Army disbands

### ISSUE THREAD

**Issue by BourgeoisieBird** [Oliveriver/5d-diplomacy-with-multiverse-time-travel#21]
Selecting a home region with two coasts (only StP by default) will sometimes make disbanding an army there impossible, as only one of the two coasts can be selected, prompting a new build prompt instead of disbanding the unit already there

**Comment by Oliveriver** [comment]
Hopefully fixed by e9e71207f9378f9fd5c110bd053109e85cafb4fd.
